package cz.sovajakub.economy.localization;

public enum LocalizationMessage {

    LOAN_ERROR_NOTIFY_GENERAL,
    LOAN_ERROR_NOTIFY_DELETE_LOAN,
    LOAN_ERROR_NOTIFY_NULL_LIST,

    LOAN_REQUEST_NOTIFY_AGREED_CREDITOR,
    LOAN_REQUEST_NOTIFY_AGREED_DEBTOR,
    LOAN_REQUEST_NOTIFY_DISAGREED_CREDITOR,
    LOAN_REQUEST_NOTIFY_DISAGREED_DEBTOR,
    LOAN_REQUEST_NOTIFY_INACTIVE,
    LOAN_REQUEST_NOTIFY_NO_MONEY,
    LOAN_REQUEST_NOTIFY_SENT,
    LOAN_REQUEST_NOTIFY_TIMED_OUT,

    LOAN_EXPIRED_NOTIFY_DEBTOR,
    LOAN_EXPIRED_NOTIFY_CREDITOR,

    LOAN_ASK_NOTIFY_WRONG_TARGET,
    LOAN_ASK_COMPONENT_OPINION,
    LOAN_ASK_COMPONENT_DEAL,
    LOAN_ASK_COMPONENT_AGREE,
    LOAN_ASK_COMPONENT_DISAGREE,

    LOAN_LIST_NOTIFY_NONE,
    LOAN_LIST_COMPONENT_HEADER,
    LOAN_LIST_COMPONENT_ROW,
    LOAN_LIST_COMPONENT_PAY,
    LOAN_LIST_COMPONENT_FOOTER,

    LOAN_PAY_INVALID_LOAN,
    LOAN_PAY_INVALID_DEBTOR,
    LOAN_PAY_NOTIFY_FAILURE_DEBTOR,
    LOAN_PAY_NOTIFY_FAILURE_CREDITOR,
    LOAN_PAY_NOTIFY_SUCCESS_DEBTOR,
    LOAN_PAY_NOTIFY_SUCCESS_CREDITOR
}